import os

# 1. Set mock env vars so build_llm passes config checks
# These values are only for building the graph structure; no real calls will happen
os.environ["INTENT.PROVIDER"] = "openai"
os.environ["INTENT.MODEL"] = "mock-model"
os.environ["PLANNER.PROVIDER"] = "openai"
os.environ["PLANNER.MODEL"] = "mock-model"
os.environ["AGENT.PROVIDER"] = "openai"
os.environ["AGENT.MODEL"] = "mock-model"
os.environ["REFLECTOR.PROVIDER"] = "openai"
os.environ["REFLECTOR.MODEL"] = "mock-model"

# Configure provider (OpenAI) settings
os.environ["LLM.PROVIDERS.OPENAI.BASE_URL"] = "https://api.mock.com/v1"
os.environ["LLM.PROVIDERS.OPENAI.API_KEY"] = "sk-mock-key"

# 2. Import build functions
try:
    from src.clawflow.agents.llm import build_llm, build_reflection_multi_agent_graph
except ImportError as e:
    print(f"Error importing modules: {e}")
    exit(1)

def generate_mermaid():
    print("Building LangGraph...")
    try:
        # Build LLM objects (all mocked)
        intent_llm, planner_llm, agent_llm, reflector_llm, responder_llm = build_llm()
        
        # Build the graph
        graph = build_reflection_multi_agent_graph(
            intent_llm, planner_llm, agent_llm, reflector_llm, responder_llm
        )
        
        # Generate Mermaid code
        # xray=1 shows subgraph structure (if any)
        mermaid_code = graph.get_graph().draw_mermaid()
        
        output_file = "graph_architecture.md"
        with open(output_file, "w", encoding="utf-8") as f:
            f.write("# LangGraph Architecture Visualization\n\n")
            f.write("Generated by `visualize_graph.py`\n\n")
            f.write("```mermaid\n")
            f.write(mermaid_code)
            f.write("\n```\n")
            
        print(f"Successfully generated Mermaid diagram to {output_file}")
        print("-" * 40)
        print(mermaid_code)
        print("-" * 40)
        
    except Exception as e:
        print(f"Failed to generate graph: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    generate_mermaid()
